[book]
authors = ["nbari"]
language = "en"
src = "src"
title = "Permesi Documentation"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
git-repository-url = "https://github.com/permesi/permesi"
edit-url-template = "https://github.com/permesi/permesi/edit/main/docs/{path}"
additional-css = ["custom.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js", "svg-pan-zoom.min.js"]
